### ISSUE TITLE
Error: `INTERNAL; CUDA driver error 'CUDA_ERROR_INVALID_VALUE' (1): invalid argument; cuLaunchKernel;`

### ISSUE THREAD

**Issue by vivekkhandelwal1** [iree-org/iree#12359]
### What happened?

Hi, I'm trying to compile and run a model on GPU via IREE, which gives the following error:
```
iree/runtime/src/iree/hal/drivers/cuda/stream_command_buffer.c:516: INTERNAL; CUDA driver error 'CUDA_ERROR_INVALID_VALUE' (1): invalid argument; cuLaunchKernel; while invoking native function hal.device.queue.execute; while calling import; 
[ 1]   native hal.device.queue.execute:0 -
[ 0] bytecode module.forward:492 cuda_failure_ir.mlir:9:10
      at cuda_failure_ir.mlir:4:3; invoking function 'forward'
```

The same IR when compiled and executed on CPU backend runs successfully.

### Steps to reproduce your issue

Smallest reproducible IR:
```
#map = affine_map<(d0, d1, d2, d3) -> (d0, d1, d2, d3)>
module attributes {torch.debug_module_name = "GraphModule"} {
  ml_program.global private mutable @global_seed(dense<0> : tensor<i64>) : tensor<i64>
  func.func @forward(%arg0: tensor<320x320x3x3xf32>) -> tensor<320x320x3x3xf32> {
    %cst = arith.constant 0.000000e+00 : f32
    %c2 = arith.constant 2 : index
    %0 = tensor.empty() : tensor<320x320x3x3xf32>
    %1 = linalg.fill ins(%cst : f32) outs(%0 : tensor<320x320x3x3xf32>) -> tensor<320x320x3x3xf32>
    %2 = linalg.generic {indexing_maps = [#map], iterator_types = ["parallel", "parallel", "parallel", "parallel"]} outs(%1 : tensor<320x320x3x3xf32>) {
    ^bb0(%out: f32):
      %3 = linalg.index 0 : index
      %4 = linalg.index 1 : index
      %5 = linalg.index 2 : index
      %6 = linalg.index 3 : index
      %7 = arith.subi %c2, %5 : index
      %8 = arith.subi %c2, %6 : index
      %extracted = tensor.extract %arg0[%4, %3, %7, %8] : tensor<320x320x3x3xf32>
      linalg.yield %extracted : f32
    } -> tensor<320x320x3x3xf32>
    return %2 : tensor<320x320x3x3xf32>
  }
}
```
For compilation run:
```
./build/tools/iree-compile --iree-input-type=none --iree-vm-bytecode-module-output-format=flatbuffer-binary --iree-hal-target-backends=cuda --mlir-print-debuginfo --mlir-print-op-on-diagnostic=false --iree-hal-cuda-llvm-target-arch=sm_80  --iree-stream-resource-index-bits=64 --iree-vm-target-index-bits=64 --iree-util-zero-fill-elided-attrs cuda_failure_ir.mlir -o cuda_failure.vmfb
```
After getting the vmfb, run the following:
```
./build/tools/iree-run-module --module=cuda_failure.vmfb --device=cuda --function=forward --input=320x320x3x3xf32
```
The above command will result in an error, as posted above.

If you compile the same IR on the CPU, use the following command:
```
./build/tools/iree-compile --iree-input-type=none --iree-vm-bytecode-module-output-format=flatbuffer-binary --iree-hal-target-backends=llvm-cpu --mlir-print-debuginfo --mlir-print-op-on-diagnostic=false -iree-llvm-target-triple=x86_64-linux-gnu --iree-stream-resource-index-bits=64 --iree-vm-target-index-bits=64 --iree-util-zero-fill-elided-attrs cuda_failure_ir.mlir -o cuda_failure_cpu.vmfb
```
and then run it via the:
```
./build/tools/iree-run-module --module=cuda_failure.vmfb --device=local-task --function=forward --input=320x320x3x3xf32
```
It will run successfully and print the resultant tensor of 0 values.

### What component(s) does this issue relate to?

MLIR, Compiler

### Version information

Git commit hash: `a1c4b9313c561c9f80d6e15ef2f01742b5bddca6`

**Comment by vivekkhandelwal1** [comment]
@ScottTodd @benvanik Could you please take a look at this issue?

**Comment by pashu123** [comment]
> @ScottTodd @benvanik Could you please take a look at this issue?

@ThomasRaoux

**Comment by ThomasRaoux** [comment]
Fixed after https://github.com/openxla/iree/pull/12368

**Comment by vivekkhandelwal1** [comment]
> Fixed after #12368

Thanks for the fix!
