### ISSUE TITLE
[Regression] `CUDA_ERROR_INVALID_VALUE` when benchmarking BertLargeTFBatch1024

### ISSUE THREAD

**Issue by mariecwhite** [iree-org/iree#13211]
### What happened?

Twice-daily benchmarking workflow failed last night when running TF BertLarge Batch 1024:

```
work/runtime/src/iree/hal/drivers/cuda/stream_command_buffer.c:516: INTERNAL; CUDA driver error 'CUDA_ERROR_INVALID_VALUE' (1): invalid argument; cuLaunchKernel; while invoking native function hal.device.queue.execute; while calling import; 
[ 1]   native hal.device.queue.execute:0 -
[ 0] bytecode module.forward:44188 [
    /work/build-e2e-test-artifacts/e2e_test_artifacts/iree_BertLargeTFBatch1024_094e620948dc85b2b15454ae696216a4e0a1128d4d3cfb2980688dc9e54e0dfe.mlir:4326:13
```

Github workflow run: https://github.com/openxla/iree/actions/runs/4752495526/jobs/8443436700

### Steps to reproduce your issue

On a machine setup to benchmark on A100:

1. Download compiled module:
```
gsutil cp gs://iree-github-actions-postsubmit-artifacts/4752495526/1/e2e-test-artifacts/iree_BertLargeTFBatch1024_module_88f03be31249d371d00c63d44d44732ad4c348bf2354bd2b3b042465d86f7183/module.vmfb /tmp
```

2. Run benchmark:
```
iree-benchmark-module --module=/tmp/module.vmfb --function=forward --input=1024x384xi32=0 --input=1024x384xi32=0 --device_allocator=caching --device=cuda://0 --benchmark_repetitions=10
```

### What component(s) does this issue relate to?

Runtime

### Version information

Commit a806149e35b04a251de8187ad3e8c11af70480f4

### Additional context

This is blocking our ability to benchmark and track performance progress.

**Comment by allieculp** [comment]
@jpienaar to help triage

**Comment by allieculp** [comment]
@mattwalsh Anyone we can assign to look at this? Blocking some benchmark tracking at the moment.

**Comment by julianwa** [comment]
@KoolJBlack has been on deck to look at these urgent GPU blocking bugs. Assigning to him

**Comment by julianwa** [comment]
Transferring to @okkwon, as @KoolJBlack is addressing other issues

**Comment by okkwon** [comment]
@mariecwhite do you know how to get the mlir and the build command?

**Comment by mariecwhite** [comment]
Download SavedModel: https://storage.googleapis.com/iree-model-artifacts/tensorflow/tf_models_2.12.0_1681767794/BERT_LARGE/batch_1024/tf-model.tar.gz

Import:
```
iree-import-tf --output-format=mlir-bytecode --tf-import-type=savedmodel_v2 --tf-savedmodel-exported-names=forward <saved_model> -o </path/to/model.mlirbc>
```

Compile:
```
iree-compile --iree-hal-target-backends=cuda --iree-input-type=mhlo --iree-hal-cuda-llvm-target-arch=sm_80 </path/to/model.mlirbc> -o </path/to/model.vmfb>
```

**Comment by pzread** [comment]
Imported MLIR can be downloaded at
```
https://storage.googleapis.com/iree-github-actions-postsubmit-artifacts/4752495526/1/e2e-test-artifacts/iree_BertLargeTFBatch1024_094e620948dc85b2b15454ae696216a4e0a1128d4d3cfb2980688dc9e54e0dfe.mlir
```

(Instructions can be found [here](https://github.com/openxla/iree/blob/main/docs/developers/developing_iree/benchmark_suites.md#find-compile-and-run-commands-to-reproduce-benchmarks))

**Comment by okkwon** [comment]
Thanks @mariecwhite @pzread!

**Comment by okkwon** [comment]
Trying to repro this on sm_86, but the compilation fails because the code uses too much memory. Is the benchmark supposed to run only on A100? If not, I will file an issue for that. 

```
iree-compile --iree-hal-target-backends=cuda --iree-input-type=mhlo --iree-hal-cuda-llvm-target-arch=sm_86 --iree-llvmgpu-shared-mem-allocation-limit=102400 iree_BertLargeTFBatch1024_094e620948dc85b2b15454ae696216a4e0a1128d4d3cfb2980688dc9e54e0dfe.mlir -o out.vmfb
...
    %564 = stablehlo.multiply %536, %563 : tensor<1024x384x4096xf32>
           ^
iree_BertLargeTFBatch1024_094e620948dc85b2b15454ae696216a4e0a1128d4d3cfb2980688dc9e54e0dfe.mlir:986:12: error: 'func.func' op exceeded GPU memory limit of 102400 bytes for function. Got 133120 bytes
    %570 = stablehlo.add %569, %530 : tensor<1024x384x1024xf32>
           ^
iree_BertLargeTFBatch1024_094e620948dc85b2b15454ae696216a4e0a1128d4d3cfb2980688dc9e54e0dfe.mlir:391:3: note: called from
  func.func @forward(%arg0: tensor<1024x384xi32>, %arg1: tensor<1024x384xi32>) -> tensor<1024x384x1024xf32> {
  ^
iree_BertLargeTFBatch1024_094e620948dc85b2b15454ae696216a4e0a1128d4d3cfb2980688dc9e54e0dfe.mlir:986:12: note: see current operation:
...
```

**Comment by mariecwhite** [comment]
I have run into instances where a model would work on an A100 but not my workstation GPU due to memory.

**Comment by okkwon** [comment]
The workgroup size x is suspiciously large: 2,415,919,104. The usual limit is 2,147,483,647.

**Comment by okkwon** [comment]
@mariecwhite Is this really a regression? What is the known good commit? I checked out the following commit, and can still reproduce the issue. 
```
a806149e35b04a251de8187ad3e8c11af70480f4 (HEAD, tag: candidate-20230420.495)
Author: mariecwhite <mariewhite@google.com>
Date:   Wed Apr 19 23:18:34 2023 -0700

    Disable models due to recent regression: https://github.com/openxla/iree/issues/13189
```

**Comment by mariecwhite** [comment]
The last known good commit is 185938135e997fb9de08b03533ae47002a5aa24e. This model succeeded in this workflow: https://github.com/openxla/iree/actions/runs/4738436854/jobs/8412643745.

**Comment by okkwon** [comment]
IIUC, that was before you added the large batch tests? If so, we may not call it a regression since we haven't tested the large configuration before.

**Comment by okkwon** [comment]
This is the problematic dispatch. We need to have a better check for the large cases and handle it correctly when the size goes beyond the limit.

https://gist.github.com/okkwon/107bbc5086720e3c0ce861b061b48531

**Comment by mariecwhite** [comment]
The large config was tested during the presubmit of the PR (https://github.com/openxla/iree/pull/12893). That's how we were able to merge it into main. It started failing shortly thereafter so I consider it a regression :)

**Comment by mariecwhite** [comment]
We also published numbers on this batch size in our monthly reporting.

**Comment by okkwon** [comment]
This is puzzling. I checked out 7758993e21c5ec4c051a596217fd1f50085fbd25, which is effectively the same commit as the passing commit, but locally it shows an error. This time, it is an out-of-memory error. I am using a100 40GB.

**Comment by okkwon** [comment]
I will use the 80GB version to faithfully reproduce the case.

**Comment by mariecwhite** [comment]
I can see why this would be confusing. You'll need to patch https://github.com/openxla/iree/pull/12893/commits/7e4763594ca3d9c0a563d90b8f73553355ea94c6 on top of https://github.com/openxla/iree/commit/185938135e997fb9de08b03533ae47002a5aa24e to do a faithful reproduction. I would have rebased that patch to head before merging.

**Comment by okkwon** [comment]
The main issue seems to be picking a wrong codegen path, WarpReduction, instead of TensorCore with unit tile sizes. When I created a unit test for the dot and the following elementwise ops, it picks bigger tile sizes with TensorCore.

**Comment by okkwon** [comment]
This is a small repro for the issue.

https://gist.github.com/okkwon/4990a09ee30493a8c3eb17c43ed65ce7

**Comment by okkwon** [comment]
This is a small repro stablehlo code. https://gist.github.com/okkwon/e5a7fa6dc30a5aec83477c2628e571f9

There are two problems: (1) performance and (2) too big workgroup count size.

The pattern is:
two elementwise add + dot_general + elementwise ops.

The funsion of tensor puts all ops into a generic op and the generic op is not detected as a contract op due to the first two elementwise-add ops pulled into the generic op, which does the dot product. This causes the GPU kernel config to detect it as a warp reduction pattern instead of a tensor-core pattern. This can be a performance problem.

The large workgroup count problem seems to be specific to the GPU warp reduction pattern and it needs more investigation to see why the codegen path picks this lowering configuration, `#iree_codegen.lowering_config<tile_sizes = [[1, 1, 1, 1], [0, 0, 0, 0, 64]]`

@MaheshRavishankar does this ring a bell to you?

**Comment by MaheshRavishankar** [comment]
https://github.com/openxla/iree/pull/13308 should fix the fusion issue

**Comment by MaheshRavishankar** [comment]
@okkwon could you prefetch #13308 and check if it helps..

**Comment by okkwon** [comment]
@MaheshRavishankar hmm. It does not help the case. Would you mind checking the stablehlo repro and see if the fusion result is what we want?

https://gist.github.com/okkwon/e5a7fa6dc30a5aec83477c2628e571f9

**Comment by MaheshRavishankar** [comment]
https://gist.github.com/MaheshRavishankar/9b3b450839b8e459149dab2ca97f78e2 is what I see with #13308 

It creates three dispatches, one each for the two inputs, one for the batch matmul + generic op fusion. That is expected.

**Comment by okkwon** [comment]
Ha, that's interesting. I will try it again with ToT. Thanks

**Comment by MaheshRavishankar** [comment]
> Ha, that's interesting. I will try it again with ToT. Thanks

not with ToT. With #13308 .

**Comment by okkwon** [comment]
My bad. I copy&pasted, but not deleted a few lines. Yes, indeed, it fixes the problem!
Closing this issue.

**Comment by MaheshRavishankar** [comment]
I still see a failure when I try to compile it locally. Maybe Marie can verify and close.

**Comment by MaheshRavishankar** [comment]
Actually see the gist above. That has the same out of memory error

**Comment by okkwon** [comment]
Oh, the OOM error is a different problem, but let's use this issue to fix that.

**Comment by okkwon** [comment]
@MaheshRavishankar I didn't get the OOM error. I saw you didn't use sm_80. The default shared memory size is set according to sm_80, but the target is not set to sm_80.

This is the command I used:
```
iree-compile --iree-hal-target-backends=cuda --iree-input-type=mhlo --iree-hal-cuda-llvm-target-arch=sm_80 repro.mlir -o repro.vmfb
```

Somehow I feel the compilation is very slow though, which may need another investigation.

**Comment by MaheshRavishankar** [comment]
We should probably fix that. But yeah that was maybe the issue. Leaving this open to investigate the slow compilation time

**Comment by julianwa** [comment]
@MaheshRavishankar, who is going to investigate the slow compilation time? We have this original issue as a P0 because it's (a) a functional regression in a key benchmark and (b) it's preventing us from collecting data in the twice-data benchmarks for this case. I'd like to get the regression described in this issue fixed asap. Is the slow compilation time a regression, and if so, how large is it?

**Comment by MaheshRavishankar** [comment]
If there is a slow compilation time, it is probably in the backend. So Kojo or Thomas?

**Comment by julianwa** [comment]
> If there is a slow compilation time, it is probably in the backend. So Kojo or Thomas?

@okkwon Please confirm whether there is a compile time regression. If the fix doesn't regress compile time, please mark this closed when the fix goes in.

**Comment by mariecwhite** [comment]
Retested and still getting the same error. Was there a patch I needed to add?

Compile is slow for all of CUDA due to https://github.com/openxla/iree/issues/13189

**Comment by MaheshRavishankar** [comment]
> Retested and still getting the same error. Was there a patch I needed to add?
> 
> Compile is slow for all of CUDA due to https://github.com/openxla/iree/issues/13189

You need https://github.com/openxla/iree/pull/13308

**Comment by mariecwhite** [comment]
I added #13308 and it has increased compilation time by >10x. What used to take 15 mins to compile ~20 models is taking >3.5 hours (still hasn't completed).

**Comment by okkwon** [comment]
It will eventually finish. Mine did over the weekend. lol

**Comment by okkwon** [comment]
@julianwa so we have two other github issue/PR to handle the build and compile time issue. Do we wanna keep this?

**Comment by julianwa** [comment]
> @julianwa so we have two other github issue/PR to handle the build and compile time issue. Do we wanna keep this?

Yes, please. Leave this issue until the fix is submitted for it. (It sounds like the fix is currently not ready to go in due to the compile time regression.)

**Comment by okkwon** [comment]
I checked my local repro to see where the explosion happens and I can confirm that LLVMGPUTensorCoreVectorization is the pass as described as https://github.com/openxla/iree/issues/13189. So the compile time issue seems to be the same one.

**Comment by MaheshRavishankar** [comment]
Thanks Okwan for the triage!

**Comment by allieculp** [comment]
@julianwa @mattwalsh Is this still considered a P0, waiting for fix? If so, need a resource.

**Comment by MaheshRavishankar** [comment]
Still a P0... it is blocking other P0 items as well.

**Comment by julianwa** [comment]
Assuming https://github.com/openxla/iree/pull/13294 is sound and goes in, I believe it's also expected to address this issue. Can you confirm @KoolJBlack ?

**Comment by vwbaker** [comment]
Has the start of this issue been narrowed down to an actual PR?

I am trying to see if it exists in https://github.com/openxla/iree/releases/tag/candidate-20230419.494, but I don't have the resources to reproduce the issue yet. It looks like the last known good commit is a few hours before this release candidate (cut at commit 8d1a7903fbfed4b5b9d06851dfa47f6358052c21), but it's unclear to me if the issue is present.

**Comment by allieculp** [comment]
Assigning to @KoolJBlack to confirm if #13294 addresses this issue.

**Comment by mattwalsh** [comment]
Per @okkwon's comment, looks like IREE, [like Vulkan](https://registry.khronos.org/vulkan/specs/1.3-extensions/man/html/VkPhysicalDeviceLimits.html), intends to store workgroups as uint32.  However when I do a cursory grep it looks like there are places where it is stored as `int32`, e.g.

`grep -rniI workgroup | grep -i int32 | grep -v uint32` gives:

```walshmatt@walshmatt-desktop:~/dev/iree$ runtime/src/iree/hal/local/executable_library_benchmark.c:31:IREE_FLAG(int32_t, workgroup_count_x, 1,
runtime/src/iree/hal/local/executable_library_benchmark.c:35:IREE_FLAG(int32_t, workgroup_count_y, 1,
runtime/src/iree/hal/local/executable_library_benchmark.c:38:IREE_FLAG(int32_t, workgroup_count_z, 1,
runtime/src/iree/hal/local/executable_library_benchmark.c:42:IREE_FLAG(int32_t, workgroup_size_x, 1,
runtime/src/iree/hal/local/executable_library_benchmark.c:44:IREE_FLAG(int32_t, workgroup_size_y, 1,
runtime/src/iree/hal/local/executable_library_benchmark.c:46:IREE_FLAG(int32_t, workgroup_size_z, 1,
runtime/src/iree/modules/hal/loader/module.c:229:      int32_t workgroup_x;
runtime/src/iree/modules/hal/loader/module.c:230:      int32_t workgroup_y;
runtime/src/iree/modules/hal/loader/module.c:231:      int32_t workgroup_z;
runtime/src/iree/task/task_test_dispatch.cc:29:        storage_(new iree_atomic_int32_t[workgroup_count_]) {
third_party/llvm-project/mlir/test/lib/Dialect/SPIRV/TestEntryPointAbi.cpp:42:  Pass::ListOption<int32_t> workgroupSize{
third_party/llvm-project/mlir/test/lib/Dialect/SPIRV/TestEntryPointAbi.cpp:58:    SmallVector<int32_t, 3> workgroupSizeVec(workgroupSize.begin(),
third_party/llvm-project/mlir/lib/Dialect/SPIRV/IR/TargetAndABI.cpp:125:                            ArrayRef<int32_t> workgroupSize,
third_party/llvm-project/mlir/lib/Dialect/GPU/Transforms/AllReduceLowering.cpp:80:    Value workgroupSize = create<arith::MulIOp>(int32Type, tmp4, dimZ);
third_party/llvm-project/mlir/lib/Dialect/GPU/Transforms/AllReduceLowering.cpp:120:        create<arith::AddIOp>(int32Type, workgroupSize, subgroupMask);
third_party/llvm-project/mlir/lib/Conversion/GPUToSPIRV/GPUToSPIRV.cpp:79:  SmallVector<int32_t, 3> workGroupSizeAsInt32;
third_party/llvm-project/mlir/lib/Conversion/GPUToSPIRV/GPUToSPIRV.cpp:209:      workGroupSizeAttr.asArrayRef()[static_cast<int32_t>(op.getDimension())];
third_party/llvm-project/mlir/include/mlir/Dialect/SPIRV/IR/TargetAndABI.h:91:                                       ArrayRef<int32_t> workgroupSize = {},
compiler/src/iree/compiler/Dialect/HAL/Target/CUDA/CUDATarget.cpp:227:    SmallVector<std::array<int32_t, 3>> workgroupSizes;
compiler/src/iree/compiler/Dialect/HAL/Target/CUDA/CUDATarget.cpp:230:      std::array<int32_t, 3> workgroupSize;
compiler/src/iree/compiler/Dialect/HAL/Target/CUDA/CUDATarget.cpp:397:        builder.createInt32Vec(workgroupLocalMemories);
compiler/src/iree/compiler/Dialect/HAL/Target/ROCM/ROCMTarget.cpp:147:    std::vector<std::array<int32_t, 3>> workgroupSizes;
compiler/src/iree/compiler/Dialect/HAL/Target/ROCM/ROCMTarget.cpp:152:      std::array<int32_t, 3> workgroupSize;
compiler/src/iree/compiler/Dialect/Vulkan/Utils/TargetEnvironment.cpp:181:      vkCapabilities.getMaxComputeWorkGroupSize().getValues<int32_t>();
```

Either way we must be water-tight and compile-time hard crash on whatever limit we mean to have.  Better yet, this might be a job for a workgroup_t type to be more explicit.

**Comment by MaheshRavishankar** [comment]
@mariecwhite this should also be fixed at ToT (by https://github.com/openxla/iree/pull/13468 ) . Please verify and close.

**Comment by mariecwhite** [comment]
This is fixed and the benchmarks have been re-enabled in https://github.com/openxla/iree/pull/13515
