### ISSUE TITLE
INTERNAL; CUDA driver error 'CUDA_ERROR_ILLEGAL_ADDRESS' (700): an illegal memory access was encountered;

### ISSUE THREAD

**Issue by vivekkhandelwal1** [iree-org/iree#13951]
### What happened?

Hi, I'm getting a runtime error while running a model via IREE. The error is as follows:
```
RuntimeError: Error invoking function: SHARK-Runtime/runtime/src/iree/hal/drivers/cuda/stream_command_buffer.c:517: INTERNAL; CUDA driver error 'CUDA_ERROR_ILLEGAL_ADDRESS' (700): an illegal memory access was encountered; cuLaunchKernel; while invoking native function hal.device.queue.execute; while calling import; 
[ 1]   native hal.device.queue.execute:0 -
[ 0] bytecode module@0:63472 -
Killed
```
After throwing the above error, it would continue to use memory and will go on to consume entire memory till the point it gets `killed`. In my case, it used the 84 GB RAM + 220 GB Swap completely before getting killed.

### Steps to reproduce your issue

To reproduce the issue, download the compiled vmfb from: https://storage.googleapis.com/shark_tank/vivek/iree_cuda_illegal_address/iree_cuda_illegal_address.vmfb

Then run the following command:
```
iree-run-module --device=cuda --module=iree_cuda_illegal_address.vmfb --function=forward --input=1x100xi64 --input=1x100xi64
```

To generate a vmfb locally, download the linalg ir from: https://storage.googleapis.com/shark_tank/vivek/iree_cuda_illegal_address/iree_cuda_illegal_address_linalg.mlir

For compilation, run the following command: 
```
./build/tools/iree-compile --iree-input-type=tm_tensor --iree-vm-bytecode-module-output-format=flatbuffer-binary --iree-hal-target-backends=cuda --iree-llvm-embedded-linker-path=iree/build/compiler/bindings/python/iree/compiler/_mlir_libs/iree-lld --mlir-print-debuginfo --mlir-print-op-on-diagnostic=false --iree-stream-resource-index-bits=64 --iree-vm-target-index-bits=64 --iree-util-zero-fill-elided-attrs iree_cuda_illegal_address_linalg.mlir -o iree_cuda_illegal_address.vmfb
```

### What component(s) does this issue relate to?

MLIR, Runtime

### Version information

```
Commit Hash: cc43680728795cb7aa87999ffecca8ec10bed682
```

**Comment by vivekkhandelwal1** [comment]
Hi, this issue is not reproducible with the latest TOM IREE. So, I'm closing this issue. Thanks!

**Comment by vivekkhandelwal1** [comment]
I'm re-opening this issue because I'm still getting this error. I have updated the description with the link to the latest vmfb and IR files. It seems this issue is similar to the given issue: https://github.com/openxla/iree/issues/13545.

Hi, @MaheshRavishankar @benvanik Can you please look at this issue as well? Or if it's a duplicate one, please let me know about the current status.

**Comment by vivekkhandelwal1** [comment]
#Update:

I have found the culprit dispatch which consumes the entire available memory till the moment it gets killed. The dispatch IR can be downloaded from here: https://storage.googleapis.com/shark_tank/vivek/iree_cuda_illegal_address/module_forward_dispatch_4_cuda_nvptx_fb.mlir, and the compiled vmfb for this dispatch is available here: https://storage.googleapis.com/shark_tank/vivek/iree_cuda_illegal_address/dispatch_4.vmfb. 

To reproduce the issue, download the dispatch IR from the above link and then run:
```
./build/tools/iree-compile --iree-input-type=none --iree-vm-bytecode-module-output-format=flatbuffer-binary --iree-hal-target-backends=cuda  --mlir-print-debuginfo --mlir-print-op-on-diagnostic=false --iree-stream-resource-index-bits=64 --iree-vm-target-index-bits=64 --iree-util-zero-fill-elided-attrs module_forward_dispatch_4_cuda_nvptx_fb.mlir -o dispatch_4.vmfb
```
After generating the vmfb locally or downloading it from the above link, run:
```
./build/tools/iree-run-module --device=cuda --module=dispatch_4.vmfb --function=forward_dispatch_4_cuda_nvptx_fb_forward_dispatch_4_generic_100x64_f32 --input=1
```
You will see that it would result in an error.

**Comment by benvanik** [comment]
@MaheshRavishankar does that dispatch look well-formed to you? I haven't seen one with two linalg.index before, and the -2 tensor.extract in there is really shady.

Thanks for narrowing it down @vivekkhandelwal1! That dispatch should just need 1211521024 * 2 bytes to complete, so I'm not sure how it could consume memory forever. How are you measuring that? A tracy trace would be useful in seeing if it's some correctness issue in the runtime or in the CUDA driver.

Does it reproduce if you compile and run the benchmark MLIR you posted? Or does it only happen in the context of the full model? The dispatch itself is interesting because it's doing a gather and maybe the indexing math is bad, and if we can isolate it then we could try running it on other targets (CPU with ASAN, etc) to see if it's a more general correctness issue or something CUDA-specific.

**Comment by vivekkhandelwal1** [comment]
> That dispatch should just need 1211521024 * 2 bytes to complete, so I'm not sure how it could consume memory forever. How are you measuring that? 

I measured the memory usage using the `htop` command on Linux. If you just run the narrowed vmfb on your system then within a few minutes it will get killed because of the memory getting exhausted.

> Does it reproduce if you compile and run the benchmark MLIR you posted?

Yeah, you can reproduce the issue locally, if you just compile and run the dispatch IR (https://storage.googleapis.com/shark_tank/vivek/iree_cuda_illegal_address/module_forward_dispatch_4_cuda_nvptx_fb.mlir) or download and run the pre-compiled vmfb for the specified dispatch (https://storage.googleapis.com/shark_tank/vivek/iree_cuda_illegal_address/dispatch_4.vmfb).

> The dispatch itself is interesting because it's doing a gather and maybe the indexing math is bad, and if we can isolate it then we could try running it on other targets (CPU with ASAN, etc) to see if it's a more general correctness issue or something CUDA-specific.

Just FYI, this runtime error is there for the CPU backend as well. On the CPU backend, it gives a segfault because of the illegal memory address access and stops running just after that. It doesn't exhaust the memory on the CPU backend.

**Comment by benvanik** [comment]
Looking at it more I think this is a miscompile higher up the stack - the `tensor.extract %6[%c0, %9, %c-2, %10] : tensor<1x100x73x64xf32>` feels wrong as it'll always be indexing off the beginning of the tensor.

```mlir
        func.func @forward_dispatch_4_generic_100x64_f32() {
          %c-2 = arith.constant -2 : index
          %c0 = arith.constant 0 : index
          %0 = hal.interface.constant.load[0] : i32
          %1 = hal.interface.constant.load[1] : i32
          %2 = arith.index_castui %0 : i32 to index
          %3 = arith.index_castui %1 : i32 to index
          %4 = hal.interface.binding.subspan set(0) binding(0) type(storage_buffer) alignment(64) offset(%2) flags(ReadOnly) : !flow.dispatch.tensor<readonly:tensor<1x100x73x64xf32>>
          %5 = hal.interface.binding.subspan set(0) binding(1) type(storage_buffer) alignment(64) offset(%3) : !flow.dispatch.tensor<writeonly:tensor<100x64xf32>>
          %6 = flow.dispatch.tensor.load %4, offsets = [0, 0, 0, 0], sizes = [1, 100, 73, 64], strides = [1, 1, 1, 1] : !flow.dispatch.tensor<readonly:tensor<1x100x73x64xf32>> -> tensor<1x100x73x64xf32>
          %7 = tensor.empty() : tensor<100x64xf32>
          %8 = linalg.generic {indexing_maps = [affine_map<(d0, d1) -> (d0, d1)>], iterator_types = ["parallel", "parallel"]} outs(%7 : tensor<100x64xf32>) {
          ^bb0(%out: f32):
            %9 = linalg.index 0 : index
            %10 = linalg.index 1 : index
            %extracted = tensor.extract %6[%c0, %9, %c-2, %10] : tensor<1x100x73x64xf32>
            linalg.yield %extracted : f32
          } -> tensor<100x64xf32>
          flow.dispatch.tensor.store %8, %5, offsets = [0, 0], sizes = [100, 64], strides = [1, 1] : tensor<100x64xf32> -> !flow.dispatch.tensor<writeonly:tensor<100x64xf32>>
          return
        }
```

If you could provide the original IR with constants stripped (50GB is a lot :) we should be able to find the issue pretty quick. You can do this by passing the MLIR through `iree-opt --mlir-elide-elementsattrs-if-larger=32 your_file.mlir > your_file_smaller.mlir` (or `iree-compile --compile-to=input --mlir-elide-elementsattrs-if-larger=32 your_file.mlir -o your_file_smaller.mlir`, but if the issue is at the HLO level it won't catch it).

(and just saw your message - yes that it happens on CPU like that is the most important signal and will make this much easier to track down - but thankfully it looks like it's even visible in the IR!)

**Comment by vivekkhandelwal1** [comment]
>
> If you could provide the original IR with constants stripped (50GB is a lot :) we should be able to find the issue pretty quick. You can do this by passing the MLIR through `iree-opt --mlir-elide-elementsattrs-if-larger=32 your_file.mlir > your_file_smaller.mlir` (or `iree-compile --compile-to=input --mlir-elide-elementsattrs-if-larger=32 your_file.mlir -o your_file_smaller.mlir`, but if the issue is at the HLO level it won't catch it).

Hi @benvanik, here's the complete elided IR: https://storage.googleapis.com/shark_tank/vivek/iree_cuda_illegal_address/iree_cuda_illegal_address_linalg_elided.mlir

**Comment by benvanik** [comment]
Thanks, very helpful! I think this may be a frontend->StableHLO(?) or StableHLO(?)->linalg error, as in this IR we can already spot the -2 sneaking in:

```
    %cst_192 = arith.constant dense<-2> : tensor<1xi64>
    %22 = tensor.empty() : tensor<1xi64>
    %23 = linalg.generic {indexing_maps = [#map8, #map9], iterator_types = ["parallel"]} ins(%cst_192 : tensor<1xi64>) outs(%22 : tensor<1xi64>) {
    ^bb0(%in: i64, %out: i64):
      linalg.yield %in : i64
    } -> tensor<1xi64>
    %24 = tensor.empty() : tensor<1x100x1x64xf32>
    %25 = linalg.generic {indexing_maps = [#map10, #map11], iterator_types = ["parallel", "parallel", "parallel", "parallel"]} ins(%23 : tensor<1xi64>) outs(%24 : tensor<1x100x1x64xf32>) {
    ^bb0(%in: i64, %out: f32):
      %1872 = linalg.index 0 : index
      %1873 = linalg.index 1 : index
      %1874 = arith.index_cast %in : i64 to index
      %1875 = linalg.index 3 : index
      %extracted = tensor.extract %expanded[%1872, %1873, %1874, %1875] : tensor<1x100x73x64xf32>
      linalg.yield %extracted : f32
    } -> tensor<1x100x1x64xf32>
```

We may have to go all the way back to your input (hopefully not all the way up to python :)
What's your pipeline look like? Is there an earlier form of the IR we can see? I'm just looking for that -2 (or what may constant fold to -2).

**Comment by benvanik** [comment]
random thought: maybe this is numpy wraparound kind of thing that isn't getting handled right - I know sometimes in python land things like [-2] really mean length - 2 - 1 (or whatever)

**Comment by vivekkhandelwal1** [comment]
> We may have to go all the way back to your input (hopefully not all the way up to python :) What's your pipeline look like? Is there an earlier form of the IR we can see? I'm just looking for that -2 (or what may constant fold to -2).

Here's the elided torch IR for the corresponding linalg IR: https://storage.googleapis.com/shark_tank/vivek/iree_cuda_illegal_address/iree_cuda_illegal_address_torch_elided.mlir

The pipeline goes this way `PyTorch_Model -> Fx_Graph -> TorchScript_Graph -> TorchScript_IR -> Torch_IR -> Linalg_IR -> IREE_Compilation -> IREE_Runtime`.

**Comment by vivekkhandelwal1** [comment]
> random thought: maybe this is numpy wraparound kind of thing that isn't getting handled right - I know sometimes in python land things like [-2] really mean length - 2 - 1 (or whatever)

The following op' seems to be culprit:

```
%192 = torch.vtensor.literal(dense<-1> : tensor<1xsi64>) : !torch.vtensor<[1],si64>
%193 = torch.vtensor.literal(dense<-2> : tensor<1xsi64>) : !torch.vtensor<[1],si64>
%224 = torch.aten.slice.Tensor %223, %int2, %int0, %int-2, %int1 : !torch.vtensor<[1,100,73,64],f32>, !torch.int, !torch.int, !torch.int, !torch.int -> !torch.vtensor<[1,100,71,64],f32>
%225 = torch.aten.clone %193, %none : !torch.vtensor<[1],si64>, !torch.none -> !torch.vtensor<[1],si64>
%226 = torch.prim.ListConstruct %none, %none, %225 : (!torch.none, !torch.none, !torch.vtensor<[1],si64>) -> !torch.list<optional<vtensor>>
%227 = torch.aten.index.Tensor %223, %226 : !torch.vtensor<[1,100,73,64],f32>, !torch.list<optional<vtensor>> -> !torch.vtensor<[1,100,1,64],f32>
%228 = torch.aten.clone %192, %none : !torch.vtensor<[1],si64>, !torch.none -> !torch.vtensor<[1],si64>
%229 = torch.prim.ListConstruct %none, %none, %228 : (!torch.none, !torch.none, !torch.vtensor<[1],si64>) -> !torch.list<optional<vtensor>>
%230 = torch.aten.index.Tensor %223, %229 : !torch.vtensor<[1,100,73,64],f32>, !torch.list<optional<vtensor>> -> !torch.vtensor<[1,100,1,64],f32>
```

**Comment by benvanik** [comment]
Hah! Yeah, was just about to post the same thing!
So I guess we need to figure out if this is something torch.aten.index.Tensor expects to work (negative indices in the list) and something that needs to be lowered differently from that into linalg (tensor.dim and affine map or something) or whether the initial lowering was supposed to do that.

https://pytorch.org/cppdocs/notes/tensor_indexing.html doesn't mention negatives but looks like they added some support at some point: https://github.com/pytorch/pytorch/issues/229
this may come from a https://pytorch.org/docs/stable/generated/torch.flip.html#torch.flip

(I'm not familiar with torch, but maybe someone else here knows - @rsuderman are you familiar with it?)

**Comment by vivekkhandelwal1** [comment]
> Hah! Yeah, was just about to post the same thing! So I guess we need to figure out if this is something torch.aten.index.Tensor expects to work (negative indices in the list) and something that needs to be lowered differently from that into linalg (tensor.dim and affine map or something) or whether the initial lowering was supposed to do that.
> 
> https://pytorch.org/cppdocs/notes/tensor_indexing.html doesn't mention negatives but looks like they added some support at some point: [pytorch/pytorch#229](https://github.com/pytorch/pytorch/issues/229) this may come from a https://pytorch.org/docs/stable/generated/torch.flip.html#torch.flip
> 
> (I'm not familiar with torch, but maybe someone else here knows - @rsuderman are you familiar with it?)

Thanks @benvanik for the help! I think this needs to be fixed in Torch-MLIR.

**Comment by vivekkhandelwal1** [comment]
> > random thought: maybe this is numpy wraparound kind of thing that isn't getting handled right - I know sometimes in python land things like [-2] really mean length - 2 - 1 (or whatever)
> 
> The following op' seems to be culprit:
> 
> ```
> %192 = torch.vtensor.literal(dense<-1> : tensor<1xsi64>) : !torch.vtensor<[1],si64>
> %193 = torch.vtensor.literal(dense<-2> : tensor<1xsi64>) : !torch.vtensor<[1],si64>
> %224 = torch.aten.slice.Tensor %223, %int2, %int0, %int-2, %int1 : !torch.vtensor<[1,100,73,64],f32>, !torch.int, !torch.int, !torch.int, !torch.int -> !torch.vtensor<[1,100,71,64],f32>
> %225 = torch.aten.clone %193, %none : !torch.vtensor<[1],si64>, !torch.none -> !torch.vtensor<[1],si64>
> %226 = torch.prim.ListConstruct %none, %none, %225 : (!torch.none, !torch.none, !torch.vtensor<[1],si64>) -> !torch.list<optional<vtensor>>
> %227 = torch.aten.index.Tensor %223, %226 : !torch.vtensor<[1,100,73,64],f32>, !torch.list<optional<vtensor>> -> !torch.vtensor<[1,100,1,64],f32>
> %228 = torch.aten.clone %192, %none : !torch.vtensor<[1],si64>, !torch.none -> !torch.vtensor<[1],si64>
> %229 = torch.prim.ListConstruct %none, %none, %228 : (!torch.none, !torch.none, !torch.vtensor<[1],si64>) -> !torch.list<optional<vtensor>>
> %230 = torch.aten.index.Tensor %223, %229 : !torch.vtensor<[1,100,73,64],f32>, !torch.list<optional<vtensor>> -> !torch.vtensor<[1,100,1,64],f32>
> ```

Hi @ramiro050, do you think that for handling this kind of op, we need to check every index value at runtime, and if negative make it a positive dim? Although I think this is not an efficient way of doing this.

**Comment by MaheshRavishankar** [comment]
Thanks @benvanik . Looking at the error, I was suspecting something like this

**Comment by vivekkhandelwal1** [comment]
This issue is fixed now with https://github.com/llvm/torch-mlir/pull/2233.
