### ISSUE TITLE
Baseline module failing during tuning: RESOURCE_EXHAUSTED; HIP driver error 'hipErrorOutOfMemory' (2): out of memory; failed to allocate buffer of length 34638106880; while invoking native function hal.allocator.allocate; while calling import;

### ISSUE THREAD

**Issue by pdhirajkumarprasad** [iree-org/iree#20518]
### What happened?

The model works fine with BS 48 in harness and even the original IR works fine with iree-benchmark-module/iree-run-module but it's failing for given IR 

```mlir
#executable_target_rocm_hsaco_fb = #hal.executable.target<"rocm", "rocm-hsaco-fb", {abi = "hip", iree.gpu.target = #iree_gpu.target<arch = "gfx942", features = "", wgp = <compute =  fp64|fp32|fp16|int64|int32|int16|int8, storage =  b64|b32|b16|b8, subgroup =  shuffle|arithmetic, dot =  dp4xi8toi32, mma = [<MFMA_F32_16x16x4_F32>, <MFMA_F32_16x16x16_F16>, <MFMA_F32_32x32x8_F16>, <MFMA_F64_16x16x4_F64>, <MFMA_F32_16x16x16_BF16>, <MFMA_F32_32x32x8_BF16>, <MFMA_F32_16x16x32_F8E5M2FNUZ>, <MFMA_F32_16x16x32_F8E5M2FNUZ_F8E4M3FNUZ>, <MFMA_F32_16x16x32_F8E4M3FNUZ>, <MFMA_F32_16x16x32_F8E4M3FNUZ_F8E5M2FNUZ>, <MFMA_F32_32x32x16_F8E5M2FNUZ>, <MFMA_F32_32x32x16_F8E5M2FNUZ_F8E4M3FNUZ>, <MFMA_F32_32x32x16_F8E4M3FNUZ>, <MFMA_F32_32x32x16_F8E4M3FNUZ_F8E5M2FNUZ>, <MFMA_I32_16x16x32_I8>, <MFMA_I32_32x32x16_I8>], subgroup_size_choices = [64], max_workgroup_sizes = [1024, 1024, 1024], max_thread_count_per_workgroup = 1024, max_workgroup_memory_bytes = 65536, max_workgroup_counts = [2147483647, 2147483647, 2147483647], max_load_instruction_bits = 128, simds_per_wgp = 4, vgpr_space_bits = 16384>>, ukernels = "none"}>
#map = affine_map<(d0, d1, d2) -> (d0, d2)>
#map1 = affine_map<(d0, d1, d2) -> (d1, d2)>
#map2 = affine_map<(d0, d1, d2) -> (d0, d1)>
#map3 = affine_map<(d0, d1) -> (d0, d1)>
#map4 = affine_map<(d0, d1) -> (d1)>
#pipeline_layout = #hal.pipeline.layout<constants = 5, bindings = [#hal.pipeline.binding<storage_buffer, "ReadOnly|Indirect">, #hal.pipeline.binding<storage_buffer, ReadOnly>, #hal.pipeline.binding<storage_buffer, Indirect>], flags = Indirect>
#device_target_hip = #hal.device.target<"hip", [#executable_target_rocm_hsaco_fb]> : !hal.device
module {
  util.global private @__device_0 = #device_target_hip
  hal.executable private @run_forward$async_dispatch_155 {
    hal.executable.variant public @rocm_hsaco_fb target(#executable_target_rocm_hsaco_fb) {
      hal.executable.export public @run_forward$async_dispatch_155_matmul_like_98304x10240x1280_i8xi8xi32 ordinal(0) layout(#pipeline_layout) {
      ^bb0(%arg0: !hal.device):
        %x, %y, %z = flow.dispatch.workgroup_count_from_slice 
        hal.return %x, %y, %z : index, index, index
      }
      builtin.module {
        func.func @run_forward$async_dispatch_155_matmul_like_98304x10240x1280_i8xi8xi32() {
          %c0_i32 = arith.constant 0 : i32
          %c4294967296_i64 = arith.constant 4294967296 : i64
          %0 = hal.interface.constant.load layout(#pipeline_layout) ordinal(0) : i32
          %1 = hal.interface.constant.load layout(#pipeline_layout) ordinal(1) : i32
          %2 = hal.interface.constant.load layout(#pipeline_layout) ordinal(2) : i32
          %3 = hal.interface.constant.load layout(#pipeline_layout) ordinal(3) : i32
          %4 = hal.interface.constant.load layout(#pipeline_layout) ordinal(4) : i32
          %5 = arith.index_castui %0 : i32 to index
          %6 = arith.index_castui %1 : i32 to index
          %7 = arith.index_castui %2 : i32 to index
          %8 = arith.index_castui %3 : i32 to index
          %9 = arith.extui %4 : i32 to i64
          %10 = arith.ori %9, %c4294967296_i64 : i64
          %11 = arith.index_castui %10 {stream.alignment = 64 : index, stream.values = [5115555904 : index, 5367214144 : index, 5618872384 : index, 5870530624 : index]} : i64 to index
          %12:5 = util.assume.int 
              %5[<umin = 3983093824, umax = 3983093824, udiv = 3983093824>, <umin = 3983093824, umax = 3983093824, udiv = 3983093824>, <umin = 3983093824, umax = 3983093824, udiv = 3983093824>, <umin = 3983093824, umax = 3983093824, udiv = 3983093824>, <umin = 3983093824, umax = 3983093824, udiv = 3983093824>, <umin = 3983093824, umax = 3983093824, udiv = 3983093824>, <umin = 3983093824, umax = 3983093824, udiv = 3983093824>, <umin = 3983093824, umax = 3983093824, udiv = 3983093824>, <umin = 3983093824, umax = 3983093824, udiv = 3983093824>, <umin = 3983093824, umax = 3983093824, udiv = 3983093824>, <umin = 3983093824, umax = 3983093824, udiv = 3983093824>, <umin = 3983093824, umax = 3983093824, udiv = 3983093824>, <umin = 3983093824, umax = 3983093824, udiv = 3983093824>, <umin = 3983093824, umax = 3983093824, udiv = 3983093824>, <umin = 3983093824, umax = 3983093824, udiv = 3983093824>, <umin = 3983093824, umax = 3983093824, udiv = 3983093824>, <umin = 3983093824, umax = 3983093824, udiv = 3983093824>, <umin = 3983093824, umax = 3983093824, udiv = 3983093824>, <umin = 3983093824, umax = 3983093824, udiv = 3983093824>, <umin = 3983093824, umax = 3983093824, udiv = 3983093824>, <umin = 3983093824, umax = 3983093824, udiv = 3983093824>, <umin = 3983093824, umax = 3983093824, udiv = 3983093824>, <umin = 3983093824, umax = 3983093824, udiv = 3983093824>, <umin = 3983093824, umax = 3983093824, udiv = 3983093824>, <umin = 3983093824, umax = 3983093824, udiv = 3983093824>, <umin = 3983093824, umax = 3983093824, udiv = 3983093824>, <umin = 3983093824, umax = 3983093824, udiv = 3983093824>, <umin = 3983093824, umax = 3983093824, udiv = 3983093824>, <umin = 3983093824, umax = 3983093824, udiv = 3983093824>, <umin = 3983093824, umax = 3983093824, udiv = 3983093824>, <umin = 3983093824, umax = 3983093824, udiv = 3983093824>, <umin = 3983093824, umax = 3983093824, udiv = 3983093824>, <umin = 3983093824, umax = 3983093824, udiv = 3983093824>, <umin = 3983093824, umax = 3983093824, udiv = 3983093824>, <umin = 3983093824, umax = 3983093824, udiv = 3983093824>, <umin = 3983093824, umax = 3983093824, udiv = 3983093824>, <umin = 3983093824, umax = 3983093824, udiv = 3983093824>, <umin = 3983093824, umax = 3983093824, udiv = 3983093824>, <umin = 3983093824, umax = 3983093824, udiv = 3983093824>, <umin = 3983093824, umax = 3983093824, udiv = 3983093824>, <umin = 3983093824, umax = 3983093824, udiv = 3983093824>, <umin = 3983093824, umax = 3983093824, udiv = 3983093824>, <umin = 3983093824, umax = 3983093824, udiv = 3983093824>, <umin = 3983093824, umax = 3983093824, udiv = 3983093824>, <umin = 3983093824, umax = 3983093824, udiv = 3983093824>, <umin = 3983093824, umax = 3983093824, udiv = 3983093824>, <umin = 3983093824, umax = 3983093824, udiv = 3983093824>, <umin = 3983093824, umax = 3983093824, udiv = 3983093824>, <umin = 3983093824, umax = 3983093824, udiv = 3983093824>, <umin = 3983093824, umax = 3983093824, udiv = 3983093824>, <umin = 3857264704, umax = 3857264704, udiv = 3857264704>, <umin = 3857264704, umax = 3857264704, udiv = 3857264704>, <umin = 3857264704, umax = 3857264704, udiv = 3857264704>, <umin = 3857264704, umax = 3857264704, udiv = 3857264704>, <umin = 3857264704, umax = 3857264704, udiv = 3857264704>, <umin = 3857264704, umax = 3857264704, udiv = 3857264704>, <umin = 3857264704, umax = 3857264704, udiv = 3857264704>, <umin = 3857264704, umax = 3857264704, udiv = 3857264704>, <umin = 3857264704, umax = 3857264704, udiv = 3857264704>, <umin = 3857264704, umax = 3857264704, udiv = 3857264704>], 
              %6[<umin = 126224768, umax = 126224768, udiv = 126224768>, <umin = 161176256, umax = 161176256, udiv = 161176256>, <umin = 196127744, umax = 196127744, udiv = 196127744>, <umin = 231079232, umax = 231079232, udiv = 231079232>, <umin = 266030720, umax = 266030720, udiv = 266030720>, <umin = 300982208, umax = 300982208, udiv = 300982208>, <umin = 335933696, umax = 335933696, udiv = 335933696>, <umin = 370885184, umax = 370885184, udiv = 370885184>, <umin = 405836672, umax = 405836672, udiv = 405836672>, <umin = 440788160, umax = 440788160, udiv = 440788160>, <umin = 511856384, umax = 511856384, udiv = 511856384>, <umin = 546807872, umax = 546807872, udiv = 546807872>, <umin = 581759360, umax = 581759360, udiv = 581759360>, <umin = 616710848, umax = 616710848, udiv = 616710848>, <umin = 651662336, umax = 651662336, udiv = 651662336>, <umin = 686613824, umax = 686613824, udiv = 686613824>, <umin = 721565312, umax = 721565312, udiv = 721565312>, <umin = 756516800, umax = 756516800, udiv = 756516800>, <umin = 791468288, umax = 791468288, udiv = 791468288>, <umin = 826419776, umax = 826419776, udiv = 826419776>, <umin = 897488000, umax = 897488000, udiv = 897488000>, <umin = 932439488, umax = 932439488, udiv = 932439488>, <umin = 967390976, umax = 967390976, udiv = 967390976>, <umin = 1002342464, umax = 1002342464, udiv = 1002342464>, <umin = 1037293952, umax = 1037293952, udiv = 1037293952>, <umin = 1072245440, umax = 1072245440, udiv = 1072245440>, <umin = 1107196928, umax = 1107196928, udiv = 1107196928>, <umin = 1142148416, umax = 1142148416, udiv = 1142148416>, <umin = 1177099904, umax = 1177099904, udiv = 1177099904>, <umin = 1212051392, umax = 1212051392, udiv = 1212051392>, <umin = 1333974208, umax = 1333974208, udiv = 1333974208>, <umin = 1368925696, umax = 1368925696, udiv = 1368925696>, <umin = 1403877184, umax = 1403877184, udiv = 1403877184>, <umin = 1438828672, umax = 1438828672, udiv = 1438828672>, <umin = 1473780160, umax = 1473780160, udiv = 1473780160>, <umin = 1508731648, umax = 1508731648, udiv = 1508731648>, <umin = 1543683136, umax = 1543683136, udiv = 1543683136>, <umin = 1578634624, umax = 1578634624, udiv = 1578634624>, <umin = 1613586112, umax = 1613586112, udiv = 1613586112>, <umin = 1648537600, umax = 1648537600, udiv = 1648537600>, <umin = 1737651328, umax = 1737651328, udiv = 1737651328>, <umin = 1772602816, umax = 1772602816, udiv = 1772602816>, <umin = 1807554304, umax = 1807554304, udiv = 1807554304>, <umin = 1842505792, umax = 1842505792, udiv = 1842505792>, <umin = 1877457280, umax = 1877457280, udiv = 1877457280>, <umin = 1912408768, umax = 1912408768, udiv = 1912408768>, <umin = 1947360256, umax = 1947360256, udiv = 1947360256>, <umin = 1982311744, umax = 1982311744, udiv = 1982311744>, <umin = 2017263232, umax = 2017263232, udiv = 2017263232>, <umin = 2052214720, umax = 2052214720, udiv = 2052214720>, <umin = 2133131328, umax = 2133131328, udiv = 2133131328>, <umin = 2168082816, umax = 2168082816, udiv = 2168082816>, <umin = 2203034304, umax = 2203034304, udiv = 2203034304>, <umin = 2237985792, umax = 2237985792, udiv = 2237985792>, <umin = 2272937280, umax = 2272937280, udiv = 2272937280>, <umin = 2307888768, umax = 2307888768, udiv = 2307888768>, <umin = 2342840256, umax = 2342840256, udiv = 2342840256>, <umin = 2377791744, umax = 2377791744, udiv = 2377791744>, <umin = 2412743232, umax = 2412743232, udiv = 2412743232>, <umin = 2447694720, umax = 2447694720, udiv = 2447694720>], 
              %7[<umin = 139331968, umax = 139331968, udiv = 139331968>, <umin = 174283456, umax = 174283456, udiv = 174283456>, <umin = 209234944, umax = 209234944, udiv = 209234944>, <umin = 244186432, umax = 244186432, udiv = 244186432>, <umin = 279137920, umax = 279137920, udiv = 279137920>, <umin = 314089408, umax = 314089408, udiv = 314089408>, <umin = 349040896, umax = 349040896, udiv = 349040896>, <umin = 383992384, umax = 383992384, udiv = 383992384>, <umin = 418943872, umax = 418943872, udiv = 418943872>, <umin = 453895360, umax = 453895360, udiv = 453895360>, <umin = 524963584, umax = 524963584, udiv = 524963584>, <umin = 559915072, umax = 559915072, udiv = 559915072>, <umin = 594866560, umax = 594866560, udiv = 594866560>, <umin = 629818048, umax = 629818048, udiv = 629818048>, <umin = 664769536, umax = 664769536, udiv = 664769536>, <umin = 699721024, umax = 699721024, udiv = 699721024>, <umin = 734672512, umax = 734672512, udiv = 734672512>, <umin = 769624000, umax = 769624000, udiv = 769624000>, <umin = 804575488, umax = 804575488, udiv = 804575488>, <umin = 839526976, umax = 839526976, udiv = 839526976>, <umin = 910595200, umax = 910595200, udiv = 910595200>, <umin = 945546688, umax = 945546688, udiv = 945546688>, <umin = 980498176, umax = 980498176, udiv = 980498176>, <umin = 1015449664, umax = 1015449664, udiv = 1015449664>, <umin = 1050401152, umax = 1050401152, udiv = 1050401152>, <umin = 1085352640, umax = 1085352640, udiv = 1085352640>, <umin = 1120304128, umax = 1120304128, udiv = 1120304128>, <umin = 1155255616, umax = 1155255616, udiv = 1155255616>, <umin = 1190207104, umax = 1190207104, udiv = 1190207104>, <umin = 1225158592, umax = 1225158592, udiv = 1225158592>, <umin = 1347081408, umax = 1347081408, udiv = 1347081408>, <umin = 1382032896, umax = 1382032896, udiv = 1382032896>, <umin = 1416984384, umax = 1416984384, udiv = 1416984384>, <umin = 1451935872, umax = 1451935872, udiv = 1451935872>, <umin = 1486887360, umax = 1486887360, udiv = 1486887360>, <umin = 1521838848, umax = 1521838848, udiv = 1521838848>, <umin = 1556790336, umax = 1556790336, udiv = 1556790336>, <umin = 1591741824, umax = 1591741824, udiv = 1591741824>, <umin = 1626693312, umax = 1626693312, udiv = 1626693312>, <umin = 1661644800, umax = 1661644800, udiv = 1661644800>, <umin = 1750758528, umax = 1750758528, udiv = 1750758528>, <umin = 1785710016, umax = 1785710016, udiv = 1785710016>, <umin = 1820661504, umax = 1820661504, udiv = 1820661504>, <umin = 1855612992, umax = 1855612992, udiv = 1855612992>, <umin = 1890564480, umax = 1890564480, udiv = 1890564480>, <umin = 1925515968, umax = 1925515968, udiv = 1925515968>, <umin = 1960467456, umax = 1960467456, udiv = 1960467456>, <umin = 1995418944, umax = 1995418944, udiv = 1995418944>, <umin = 2030370432, umax = 2030370432, udiv = 2030370432>, <umin = 2065321920, umax = 2065321920, udiv = 2065321920>, <umin = 2146238528, umax = 2146238528, udiv = 2146238528>, <umin = 2181190016, umax = 2181190016, udiv = 2181190016>, <umin = 2216141504, umax = 2216141504, udiv = 2216141504>, <umin = 2251092992, umax = 2251092992, udiv = 2251092992>, <umin = 2286044480, umax = 2286044480, udiv = 2286044480>, <umin = 2320995968, umax = 2320995968, udiv = 2320995968>, <umin = 2355947456, umax = 2355947456, udiv = 2355947456>, <umin = 2390898944, umax = 2390898944, udiv = 2390898944>, <umin = 2425850432, umax = 2425850432, udiv = 2425850432>, <umin = 2460801920, umax = 2460801920, udiv = 2460801920>], 
              %8[<umin = 139372928, umax = 139372928, udiv = 139372928>, <umin = 174324416, umax = 174324416, udiv = 174324416>, <umin = 209275904, umax = 209275904, udiv = 209275904>, <umin = 244227392, umax = 244227392, udiv = 244227392>, <umin = 279178880, umax = 279178880, udiv = 279178880>, <umin = 314130368, umax = 314130368, udiv = 314130368>, <umin = 349081856, umax = 349081856, udiv = 349081856>, <umin = 384033344, umax = 384033344, udiv = 384033344>, <umin = 418984832, umax = 418984832, udiv = 418984832>, <umin = 453936320, umax = 453936320, udiv = 453936320>, <umin = 525004544, umax = 525004544, udiv = 525004544>, <umin = 559956032, umax = 559956032, udiv = 559956032>, <umin = 594907520, umax = 594907520, udiv = 594907520>, <umin = 629859008, umax = 629859008, udiv = 629859008>, <umin = 664810496, umax = 664810496, udiv = 664810496>, <umin = 699761984, umax = 699761984, udiv = 699761984>, <umin = 734713472, umax = 734713472, udiv = 734713472>, <umin = 769664960, umax = 769664960, udiv = 769664960>, <umin = 804616448, umax = 804616448, udiv = 804616448>, <umin = 839567936, umax = 839567936, udiv = 839567936>, <umin = 910636160, umax = 910636160, udiv = 910636160>, <umin = 945587648, umax = 945587648, udiv = 945587648>, <umin = 980539136, umax = 980539136, udiv = 980539136>, <umin = 1015490624, umax = 1015490624, udiv = 1015490624>, <umin = 1050442112, umax = 1050442112, udiv = 1050442112>, <umin = 1085393600, umax = 1085393600, udiv = 1085393600>, <umin = 1120345088, umax = 1120345088, udiv = 1120345088>, <umin = 1155296576, umax = 1155296576, udiv = 1155296576>, <umin = 1190248064, umax = 1190248064, udiv = 1190248064>, <umin = 1225199552, umax = 1225199552, udiv = 1225199552>, <umin = 1347122368, umax = 1347122368, udiv = 1347122368>, <umin = 1382073856, umax = 1382073856, udiv = 1382073856>, <umin = 1417025344, umax = 1417025344, udiv = 1417025344>, <umin = 1451976832, umax = 1451976832, udiv = 1451976832>, <umin = 1486928320, umax = 1486928320, udiv = 1486928320>, <umin = 1521879808, umax = 1521879808, udiv = 1521879808>, <umin = 1556831296, umax = 1556831296, udiv = 1556831296>, <umin = 1591782784, umax = 1591782784, udiv = 1591782784>, <umin = 1626734272, umax = 1626734272, udiv = 1626734272>, <umin = 1661685760, umax = 1661685760, udiv = 1661685760>, <umin = 1750799488, umax = 1750799488, udiv = 1750799488>, <umin = 1785750976, umax = 1785750976, udiv = 1785750976>, <umin = 1820702464, umax = 1820702464, udiv = 1820702464>, <umin = 1855653952, umax = 1855653952, udiv = 1855653952>, <umin = 1890605440, umax = 1890605440, udiv = 1890605440>, <umin = 1925556928, umax = 1925556928, udiv = 1925556928>, <umin = 1960508416, umax = 1960508416, udiv = 1960508416>, <umin = 1995459904, umax = 1995459904, udiv = 1995459904>, <umin = 2030411392, umax = 2030411392, udiv = 2030411392>, <umin = 2065362880, umax = 2065362880, udiv = 2065362880>, <umin = 2146279488, umax = 2146279488, udiv = 2146279488>, <umin = 2181230976, umax = 2181230976, udiv = 2181230976>, <umin = 2216182464, umax = 2216182464, udiv = 2216182464>, <umin = 2251133952, umax = 2251133952, udiv = 2251133952>, <umin = 2286085440, umax = 2286085440, udiv = 2286085440>, <umin = 2321036928, umax = 2321036928, udiv = 2321036928>, <umin = 2355988416, umax = 2355988416, udiv = 2355988416>, <umin = 2390939904, umax = 2390939904, udiv = 2390939904>, <umin = 2425891392, umax = 2425891392, udiv = 2425891392>, <umin = 2460842880, umax = 2460842880, udiv = 2460842880>], 
              %11[<umin = 5115555904, umax = 5115555904, udiv = 5115555904>, <umin = 5367214144, umax = 5367214144, udiv = 5367214144>, <umin = 5115555904, umax = 5115555904, udiv = 5115555904>, <umin = 5367214144, umax = 5367214144, udiv = 5367214144>, <umin = 5115555904, umax = 5115555904, udiv = 5115555904>, <umin = 5367214144, umax = 5367214144, udiv = 5367214144>, <umin = 5115555904, umax = 5115555904, udiv = 5115555904>, <umin = 5367214144, umax = 5367214144, udiv = 5367214144>, <umin = 5115555904, umax = 5115555904, udiv = 5115555904>, <umin = 5367214144, umax = 5367214144, udiv = 5367214144>, <umin = 5367214144, umax = 5367214144, udiv = 5367214144>, <umin = 5618872384, umax = 5618872384, udiv = 5618872384>, <umin = 5367214144, umax = 5367214144, udiv = 5367214144>, <umin = 5618872384, umax = 5618872384, udiv = 5618872384>, <umin = 5367214144, umax = 5367214144, udiv = 5367214144>, <umin = 5618872384, umax = 5618872384, udiv = 5618872384>, <umin = 5367214144, umax = 5367214144, udiv = 5367214144>, <umin = 5618872384, umax = 5618872384, udiv = 5618872384>, <umin = 5367214144, umax = 5367214144, udiv = 5367214144>, <umin = 5618872384, umax = 5618872384, udiv = 5618872384>, <umin = 5618872384, umax = 5618872384, udiv = 5618872384>, <umin = 5870530624, umax = 5870530624, udiv = 5870530624>, <umin = 5618872384, umax = 5618872384, udiv = 5618872384>, <umin = 5870530624, umax = 5870530624, udiv = 5870530624>, <umin = 5618872384, umax = 5618872384, udiv = 5618872384>, <umin = 5870530624, umax = 5870530624, udiv = 5870530624>, <umin = 5618872384, umax = 5618872384, udiv = 5618872384>, <umin = 5870530624, umax = 5870530624, udiv = 5870530624>, <umin = 5618872384, umax = 5618872384, udiv = 5618872384>, <umin = 5870530624, umax = 5870530624, udiv = 5870530624>, <umin = 5367214144, umax = 5367214144, udiv = 5367214144>, <umin = 5618872384, umax = 5618872384, udiv = 5618872384>, <umin = 5367214144, umax = 5367214144, udiv = 5367214144>, <umin = 5618872384, umax = 5618872384, udiv = 5618872384>, <umin = 5367214144, umax = 5367214144, udiv = 5367214144>, <umin = 5618872384, umax = 5618872384, udiv = 5618872384>, <umin = 5367214144, umax = 5367214144, udiv = 5367214144>, <umin = 5618872384, umax = 5618872384, udiv = 5618872384>, <umin = 5367214144, umax = 5367214144, udiv = 5367214144>, <umin = 5618872384, umax = 5618872384, udiv = 5618872384>, <umin = 5115555904, umax = 5115555904, udiv = 5115555904>, <umin = 5367214144, umax = 5367214144, udiv = 5367214144>, <umin = 5115555904, umax = 5115555904, udiv = 5115555904>, <umin = 5367214144, umax = 5367214144, udiv = 5367214144>, <umin = 5115555904, umax = 5115555904, udiv = 5115555904>, <umin = 5367214144, umax = 5367214144, udiv = 5367214144>, <umin = 5115555904, umax = 5115555904, udiv = 5115555904>, <umin = 5367214144, umax = 5367214144, udiv = 5367214144>, <umin = 5115555904, umax = 5115555904, udiv = 5115555904>, <umin = 5367214144, umax = 5367214144, udiv = 5367214144>, <umin = 5115555904, umax = 5115555904, udiv = 5115555904>, <umin = 5115555904, umax = 5115555904, udiv = 5115555904>, <umin = 5115555904, umax = 5115555904, udiv = 5115555904>, <umin = 5115555904, umax = 5115555904, udiv = 5115555904>, <umin = 5115555904, umax = 5115555904, udiv = 5115555904>, <umin = 5115555904, umax = 5115555904, udiv = 5115555904>, <umin = 5115555904, umax = 5115555904, udiv = 5115555904>, <umin = 5115555904, umax = 5115555904, udiv = 5115555904>, <umin = 5115555904, umax = 5115555904, udiv = 5115555904>, <umin = 5115555904, umax = 5115555904, udiv = 5115555904>]
            : index, index, index, index, index
          %13 = hal.interface.binding.subspan layout(#pipeline_layout) binding(0) alignment(64) offset(%12#0) flags("ReadOnly|Indirect") {iree_gpu.use_rocdl_buffer_instructions} : !flow.dispatch.tensor<readonly:tensor<98304x1280xi8>>
          %14 = hal.interface.binding.subspan layout(#pipeline_layout) binding(1) alignment(64) offset(%12#1) flags(ReadOnly) {iree_gpu.use_rocdl_buffer_instructions} : !flow.dispatch.tensor<readonly:tensor<10240x1280xi8>>
          %15 = hal.interface.binding.subspan layout(#pipeline_layout) binding(1) alignment(64) offset(%12#2) flags(ReadOnly) {iree_gpu.use_rocdl_buffer_instructions} : !flow.dispatch.tensor<readonly:tensor<10240xi32>>
          %16 = hal.interface.binding.subspan layout(#pipeline_layout) binding(1) alignment(64) offset(%12#3) flags(ReadOnly) {iree_gpu.use_rocdl_buffer_instructions} : !flow.dispatch.tensor<readonly:tensor<10240xf32>>
          %17 = hal.interface.binding.subspan layout(#pipeline_layout) binding(2) alignment(64) offset(%12#4) flags(Indirect) {iree_gpu.use_rocdl_buffer_instructions} : !flow.dispatch.tensor<writeonly:tensor<98304x10240xf16>>
          %18 = flow.dispatch.tensor.load %13, offsets = [0, 0], sizes = [98304, 1280], strides = [1, 1] : !flow.dispatch.tensor<readonly:tensor<98304x1280xi8>> -> tensor<98304x1280xi8>
          %19 = flow.dispatch.tensor.load %14, offsets = [0, 0], sizes = [10240, 1280], strides = [1, 1] : !flow.dispatch.tensor<readonly:tensor<10240x1280xi8>> -> tensor<10240x1280xi8>
          %20 = flow.dispatch.tensor.load %15, offsets = [0], sizes = [10240], strides = [1] : !flow.dispatch.tensor<readonly:tensor<10240xi32>> -> tensor<10240xi32>
          %21 = flow.dispatch.tensor.load %16, offsets = [0], sizes = [10240], strides = [1] : !flow.dispatch.tensor<readonly:tensor<10240xf32>> -> tensor<10240xf32>
          %22 = tensor.empty() : tensor<98304x10240xi32>
          %23 = linalg.fill ins(%c0_i32 : i32) outs(%22 : tensor<98304x10240xi32>) -> tensor<98304x10240xi32>
          %24 = linalg.generic {indexing_maps = [#map, #map1, #map2], iterator_types = ["parallel", "parallel", "reduction"]} ins(%18, %19 : tensor<98304x1280xi8>, tensor<10240x1280xi8>) outs(%23 : tensor<98304x10240xi32>) {
          ^bb0(%in: i8, %in_0: i8, %out: i32):
            %27 = arith.extsi %in : i8 to i32
            %28 = arith.extsi %in_0 : i8 to i32
            %29 = arith.muli %27, %28 : i32
            %30 = arith.addi %out, %29 : i32
            linalg.yield %30 : i32
          } -> tensor<98304x10240xi32>
          %25 = tensor.empty() : tensor<98304x10240xf16>
          %26 = linalg.generic {indexing_maps = [#map3, #map4, #map4, #map3], iterator_types = ["parallel", "parallel"]} ins(%24, %20, %21 : tensor<98304x10240xi32>, tensor<10240xi32>, tensor<10240xf32>) outs(%25 : tensor<98304x10240xf16>) {
          ^bb0(%in: i32, %in_0: i32, %in_1: f32, %out: f16):
            %27 = arith.addi %in, %in_0 : i32
            %28 = arith.sitofp %27 : i32 to f32
            %29 = arith.mulf %28, %in_1 : f32
            %30 = arith.truncf %29 : f32 to f16
            linalg.yield %30 : f16
          } -> tensor<98304x10240xf16>
          flow.dispatch.tensor.store %26, %17, offsets = [0, 0], sizes = [98304, 10240], strides = [1, 1] : tensor<98304x10240xf16> -> !flow.dispatch.tensor<writeonly:tensor<98304x10240xf16>>
          return
        }
      }
    }
  }
  util.global private mutable @run_forward$async_dispatch_155_rocm_hsaco_fb_run_forward$async_dispatch_155_matmul_like_98304x10240x1280_i8xi8xi32_buffer : !hal.buffer
  util.initializer {
    %device, %queue_affinity = hal.device.resolve on(<@__device_0>) : !hal.device, i64
    %allocator = hal.device.allocator<%device : !hal.device> : !hal.allocator
    %c34638106880 = arith.constant 34638106880 : index
    %buffer = hal.allocator.allocate<%allocator : !hal.allocator> affinity(%queue_affinity) type("DeviceVisible|DeviceLocal") usage("TransferSource|TransferTarget|Transfer|DispatchStorageRead|DispatchStorageWrite|DispatchStorage") : !hal.buffer{%c34638106880}
    util.global.store %buffer, @run_forward$async_dispatch_155_rocm_hsaco_fb_run_forward$async_dispatch_155_matmul_like_98304x10240x1280_i8xi8xi32_buffer : !hal.buffer
    util.return
  }
  util.func public @run_forward$async_dispatch_155_rocm_hsaco_fb_run_forward$async_dispatch_155_matmul_like_98304x10240x1280_i8xi8xi32(%arg0: i32) attributes {iree.abi.stub, iree.reflection = {iree.benchmark = "dispatch"}} {
    %0 = arith.index_cast %arg0 : i32 to index
    %device, %queue_affinity = hal.device.resolve on(<@__device_0>) : !hal.device, i64
    %cmd = hal.command_buffer.create device(%device : !hal.device) mode("OneShot|AllowInlineExecution") categories(Dispatch) affinity(%queue_affinity) : !hal.command_buffer
    %c-437702592_i32 = arith.constant -437702592 : i32
    %c-1847272576_i32 = arith.constant -1847272576 : i32
    %c-1834165376_i32 = arith.constant -1834165376 : i32
    %c-1834124416_i32 = arith.constant -1834124416 : i32
    %c820588608_i32 = arith.constant 820588608 : i32
    %run_forward$async_dispatch_155_rocm_hsaco_fb_run_forward$async_dispatch_155_matmul_like_98304x10240x1280_i8xi8xi32_buffer = util.global.load @run_forward$async_dispatch_155_rocm_hsaco_fb_run_forward$async_dispatch_155_matmul_like_98304x10240x1280_i8xi8xi32_buffer : !hal.buffer
    %c0 = arith.constant 0 : index
    %c16016117824 = arith.constant 16016117824 : index
    %c16016118016 = arith.constant 16016118016 : index
    %c2605870784 = arith.constant 2605870784 : index
    %c18621988864 = arith.constant 18621988864 : index
    %workgroup_x, %workgroup_y, %workgroup_z = hal.executable.calculate_workgroups device(%device : !hal.device) target(@run_forward$async_dispatch_155::@rocm_hsaco_fb::@run_forward$async_dispatch_155_matmul_like_98304x10240x1280_i8xi8xi32) : index, index, index
    %exe = hal.executable.lookup device(%device : !hal.device) executable(@run_forward$async_dispatch_155) : !hal.executable
    %ordinal = hal.executable.export.ordinal target(@run_forward$async_dispatch_155::@rocm_hsaco_fb::@run_forward$async_dispatch_155_matmul_like_98304x10240x1280_i8xi8xi32) : index
    %c1 = arith.constant 1 : index
    scf.for %arg1 = %c0 to %0 step %c1 {
      hal.command_buffer.dispatch<%cmd : !hal.command_buffer> target(%exe : !hal.executable)[%ordinal] workgroups([%workgroup_x, %workgroup_y, %workgroup_z]) constants([%c-437702592_i32, %c-1847272576_i32, %c-1834165376_i32, %c-1834124416_i32, %c820588608_i32]) bindings([
        (%run_forward$async_dispatch_155_rocm_hsaco_fb_run_forward$async_dispatch_155_matmul_like_98304x10240x1280_i8xi8xi32_buffer : !hal.buffer)[%c0, %c16016117824], 
        (%run_forward$async_dispatch_155_rocm_hsaco_fb_run_forward$async_dispatch_155_matmul_like_98304x10240x1280_i8xi8xi32_buffer : !hal.buffer)[%c16016118016, %c2605870784], 
        (%run_forward$async_dispatch_155_rocm_hsaco_fb_run_forward$async_dispatch_155_matmul_like_98304x10240x1280_i8xi8xi32_buffer : !hal.buffer)[%c18621988864, %c16016117824]
      ]) flags("None")
      hal.command_buffer.execution_barrier<%cmd : !hal.command_buffer> source("Dispatch|CommandRetire") target("CommandIssue|Dispatch") flags("None")
    }
    hal.command_buffer.finalize<%cmd : !hal.command_buffer>
    %1 = util.null : !hal.fence
    %fence = hal.fence.create device(%device : !hal.device) flags("None") : !hal.fence
    hal.device.queue.execute<%device : !hal.device> affinity(%queue_affinity) wait(%1) signal(%fence) commands(%cmd) flags("None")
    %c-1_i32 = arith.constant -1 : i32
    %status = hal.fence.await until([%fence]) timeout_millis(%c-1_i32) flags("None") : i32
    util.status.check_ok %status, "failed to wait on timepoint"
    util.return
  }
}

{-#
  external_resources: {
    mlir_reproducer: {
      pipeline: "builtin.module(iree-hal-assign-legacy-target-devices{target-registry=1 targetBackends={rocm}}, iree-hal-materialize-target-devices{defaultDevice=}, iree-hal-resolve-device-promises, iree-hal-resolve-device-aliases{target-registry=1}, iree-hal-verify-devices{target-registry=1}, hal.executable(iree-hal-configure-executables{target-registry=1},iree-hal-translate-all-executables{target-registry=1}), iree-hal-conversion, iree-hal-outline-memoize-regions, iree-hal-prune-executables, func.func(canonicalize{  max-iterations=10 max-num-rewrites=-1 region-simplify=normal test-convergence=false top-down=true},cse,iree-util-simplify-global-accesses,iree-util-apply-patterns),util.func(canonicalize{  max-iterations=10 max-num-rewrites=-1 region-simplify=normal test-convergence=false top-down=true},cse,iree-util-simplify-global-accesses,iree-util-apply-patterns),util.initializer(canonicalize{  max-iterations=10 max-num-rewrites=-1 region-simplify=normal test-convergence=false top-down=true},cse,iree-util-simplify-global-accesses,iree-util-apply-patterns), iree-util-fold-globals, iree-util-fuse-globals, iree-hal-link-all-executables{target-registry=1}, hal.executable(hal.executable.variant(iree-hal-hoist-executable-objects)), iree-hal-resolve-export-ordinals, iree-hal-materialize-resource-caches, iree-hal-memoize-device-queries, func.func(canonicalize{  max-iterations=10 max-num-rewrites=-1 region-simplify=normal test-convergence=false top-down=true},cse,iree-util-simplify-global-accesses,iree-util-apply-patterns),util.func(canonicalize{  max-iterations=10 max-num-rewrites=-1 region-simplify=normal test-convergence=false top-down=true},cse,iree-util-simplify-global-accesses,iree-util-apply-patterns),util.initializer(canonicalize{  max-iterations=10 max-num-rewrites=-1 region-simplify=normal test-convergence=false top-down=true},cse,iree-util-simplify-global-accesses,iree-util-apply-patterns), iree-util-fold-globals, iree-util-fuse-globals, func.func(iree-hal-elide-redundant-commands),util.func(iree-hal-elide-redundant-commands),util.initializer(iree-hal-elide-redundant-commands), iree-hal-initialize-devices{target-registry=1}, affine-expand-index-ops, lower-affine, func.func(convert-scf-to-cf),hal.executable(iree-hal-serialize-all-executables{debug-level=2 dump-binaries-path= dump-intermediates-path= target-registry=1}),util.func(convert-scf-to-cf),util.initializer(convert-scf-to-cf), iree-hal-prune-executables, symbol-dce, iree-util-fixed-point-iterator{max-iterations=10 pipeline=builtin.module(func.func(canonicalize{  max-iterations=10 max-num-rewrites=-1 region-simplify=normal test-convergence=false top-down=true},cse,iree-util-simplify-global-accesses,iree-util-apply-patterns),util.initializer(canonicalize{  max-iterations=10 max-num-rewrites=-1 region-simplify=normal test-convergence=false top-down=true},cse,iree-util-simplify-global-accesses,iree-util-apply-patterns),util.func(canonicalize{  max-iterations=10 max-num-rewrites=-1 region-simplify=normal test-convergence=false top-down=true},cse,iree-util-simplify-global-accesses,iree-util-apply-patterns),iree-util-fold-globals,iree-util-fuse-globals,iree-util-ipo)}, inline{default-pipeline=canonicalize inlining-threshold=4294967295 max-iterations=4 }, symbol-dce, iree-util-combine-initializers, func.func(scf-for-loop-canonicalization,affine-loop-coalescing,loop-invariant-code-motion,convert-scf-to-cf,affine-expand-index-ops,lower-affine,arith-unsigned-when-equivalent),util.func(scf-for-loop-canonicalization,loop-invariant-code-motion,convert-scf-to-cf,affine-expand-index-ops,lower-affine,arith-unsigned-when-equivalent),util.initializer(scf-for-loop-canonicalization,loop-invariant-code-motion,convert-scf-to-cf,affine-expand-index-ops,lower-affine,arith-unsigned-when-equivalent), iree-util-propagate-subranges, func.func(canonicalize{  max-iterations=10 max-num-rewrites=-1 region-simplify=normal test-convergence=false top-down=true},cse),util.func(canonicalize{  max-iterations=10 max-num-rewrites=-1 region-simplify=normal test-convergence=false top-down=true},cse),util.initializer(canonicalize{  max-iterations=10 max-num-rewrites=-1 region-simplify=normal test-convergence=false top-down=true},cse),vm.module(iree-vm-drop-unused-calls), symbol-dce, func.func(iree-util-simplify-global-accesses,iree-util-apply-patterns),util.func(iree-util-simplify-global-accesses,iree-util-apply-patterns),util.initializer(iree-util-simplify-global-accesses,iree-util-apply-patterns), iree-util-fold-globals, iree-util-fuse-globals, iree-vm-conversion, func.func(canonicalize{  max-iterations=10 max-num-rewrites=-1 region-simplify=normal test-convergence=false top-down=true},cse),util.func(canonicalize{  max-iterations=10 max-num-rewrites=-1 region-simplify=normal test-convergence=false top-down=true},cse),util.initializer(canonicalize{  max-iterations=10 max-num-rewrites=-1 region-simplify=normal test-convergence=false top-down=true},cse),vm.module(iree-vm-reify-rodata-tables,iree-vm-hoist-inlined-rodata,iree-vm-deduplicate-rodata,iree-vm-drop-unused-calls), symbol-dce, func.func(iree-util-simplify-global-accesses,iree-util-apply-patterns),util.func(iree-util-simplify-global-accesses,iree-util-apply-patterns),util.initializer(iree-util-simplify-global-accesses,iree-util-apply-patterns), iree-util-fold-globals, iree-util-fuse-globals, vm.module(iree-vm-resolve-rodata-loads), inline{default-pipeline=canonicalize inlining-threshold=4294967295 max-iterations=4 }, symbol-dce, func.func(canonicalize{  max-iterations=10 max-num-rewrites=-1 region-simplify=normal test-convergence=false top-down=true},cse),util.func(canonicalize{  max-iterations=10 max-num-rewrites=-1 region-simplify=normal test-convergence=false top-down=true},cse),util.initializer(canonicalize{  max-iterations=10 max-num-rewrites=-1 region-simplify=normal test-convergence=false top-down=true},cse),vm.module(iree-vm-drop-unused-calls), symbol-dce, func.func(iree-util-simplify-global-accesses,iree-util-apply-patterns),util.func(iree-util-simplify-global-accesses,iree-util-apply-patterns),util.initializer(iree-util-simplify-global-accesses,iree-util-apply-patterns), iree-util-fold-globals, iree-util-fuse-globals, vm.module(iree-vm-global-initialization), canonicalize{  max-iterations=10 max-num-rewrites=-1 region-simplify=normal test-convergence=false top-down=true}, cse, canonicalize{  max-iterations=10 max-num-rewrites=-1 region-simplify=normal test-convergence=false top-down=true}, vm.module(iree-vm-drop-empty-module-initializers), iree-util-drop-compiler-hints)",
      disable_threading: false,
      verify_each: true
    }
  }
#-}
```

command:

```
iree-compile 1.vmfb.crash_report.mlir --iree-hal-target-backends=rocm --iree-hip-target=gfx942 --iree-vm-bytecode-module-output-format=flatbuffer-binary --iree-dispatch-creation-enable-aggressive-fusion --iree-dispatch-creation-enable-fuse-horizontal-contractions=false --iree-opt-aggressively-propagate-transposes=true --iree-codegen-llvmgpu-use-vector-distribution=true --iree-opt-data-tiling=false --iree-vm-target-truncate-unsupported-floats --iree-opt-outer-dim-concat=true --iree-codegen-gpu-native-math-precision=true --iree-hal-indirect-command-buffers=true --iree-stream-resource-memory-model=discrete --iree-hal-memoization=true --iree-opt-strip-assertions --iree-global-opt-propagate-transposes=true --iree-opt-const-eval=false --iree-llvmgpu-enable-prefetch=true --iree-execution-model=async-external --iree-preprocessing-pass-pipeline='builtin.module(util.func(iree-global-opt-raise-special-ops, iree-flow-canonicalize), iree-preprocessing-transpose-convolution-pipeline, iree-preprocessing-pad-to-intrinsics, util.func(iree-preprocessing-generalize-linalg-matmul-experimental))' -o out.vmfb

iree-benchmark-module --module=./out.vmfb --device=hip --input=48x4x128x128xf16 --input=96x64x2048xf16 --input=96x1280xf16 --input=96x6xf16 --input=1xf16 --input=1xi64 --input=100xf32  --parameters=model=/data/mlperf_sdxl/models/SDXL/official_pytorch/fp16/stable_diffusion_fp16/genfiles/sdxl/stable_diffusion_xl_base_1_0_punet_dataset_i8.irpa --function=run_forward
```

IREE version: 9c12d1dc21c39b1e19032d4e37646fc28ac8abf5

**Comment by AWoloszyn** [comment]
It depends what machine you are running this one, but it's trying to allocate 34GB of memory, if you are in CPX mode on any device I would not expect this to work. 
If you are on SPX mode then we likely have a bug. Can you confirm the configuration of the machine in question?

**Comment by qedawkins** [comment]
There is something strange with the `iree-hal-dump-executable-benchmarks`. The amount of memory required by the dispatch (`98304 * 10240 * 2 + 10240 * 8 + 10240 * 1280 + 98304 * 1280 = 2152284160 = ~2GB`) is far less than the amount being allocated (`16016117824 + 2605870784 + 16016117824 = ~34GB`).

**Comment by qedawkins** [comment]
> It depends what machine you are running this one, but it's trying to allocate 34GB of memory, if you are in CPX mode on any device I would not expect this to work. If you are on SPX mode then we likely have a bug. Can you confirm the configuration of the machine in question?

Agree, there is no fix in the compiler for the above IR. If there is something to fix it will be in the logic that dumps executable benchmarks, which needs the original IR. @pdhirajkumarprasad can you share the IR + command that produced this benchmark IR?

**Comment by pdhirajkumarprasad** [comment]
I tried with `--iree-scheduling-optimize-bindings=false` and with this it's working now
